name: Lint Code

on:
  pull_request:
    branches: [dev]

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}

      - uses: actions/setup-node@v3
        with:
          node-version: "20"
          cache: "yarn"

      - run: yarn install
      - run: yarn lint

  autofix:
    needs: lint
    runs-on: ubuntu-latest
    if: github.actor != 'github-actions' && github.event_name == 'pull_request'

    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "20"

      - run: yarn install
      - run: yarn pretest

      - name: Commit fixes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git add .
          git diff --cached --quiet || {
            git commit -m "style: auto-fix lint issues"
            git pull --rebase origin ${{ github.head_ref }}
            git push origin HEAD:${{ github.head_ref }}
          }
        env:
          GITHUX_TOKEN: ${{ secrets.GITHUB_TOKEN }}
